--employees 

SELECT * FROM EMPLOYEES e ;
SELECT first_name, LAST_name, job_id FROM EMPLOYEES e;

SELECT EMPLOYEE_ID, LAST_NAME, SALARY FROM EMPLOYEES WHERE EMPLOYEE_ID = 176 ;
SELECT LAST_NAME , salary FROM EMPLOYEES WHERE SALARY >= 12000;
SELECT Last_name, salary FROM EMPLOYEES WHERE SALARY < 5000 OR SALARY > 12000;

SELECT
	LAST_NAME ,
	DEPARTMENT_ID
FROM
	EMPLOYEES
WHERE
	DEPARTMENT_ID IN (20, 50)
ORDER BY
	LAST_NAME,
	DEPARTMENT_ID;

SELECT
	LAST_NAME,
	salary,
	COMMISSION_PCT
FROM
	EMPLOYEES
WHERE
	COMMISSION_PCT IS NOT NULL;

SELECT
	*
FROM
	EMPLOYEES
WHERE
	SALARY NOT IN (2500, 3500, 7000)
	AND JOB_ID IN ('SA_REP', 'ST_CLERK');

SELECT LAST_NAME , EMPLOYEE_ID , HIRE_DATE  FROM EMPLOYEES WHERE HIRE_DATE > '2017-01-01' AND HIRE_DATE < '2017-12-31';

SELECT Last_name, salary FROM EMPLOYEES WHERE SALARY BETWEEN 5000 AND 12000 ORDER BY SALARY ASC ;
SELECT LAST_NAME , EMPLOYEE_ID , HIRE_DATE  FROM EMPLOYEES WHERE HIRE_DATE BETWEEN '2017-01-01' AND '2017-12-31' ORDER BY HIRE_DATE ;

SELECT EMPLOYEE_ID , LAST_NAME FROM EMPLOYEES e WHERE LAST_NAME LIKE '%u%';
SELECT EMPLOYEE_ID , LAST_NAME FROM EMPLOYEES e WHERE LAST_NAME LIKE '___a%';
SELECT EMPLOYEE_ID , LAST_NAME FROM EMPLOYEES e WHERE LAST_NAME LIKE '%a%e%' ORDER BY LAST_NAME ASC;

SELECT LAST_NAME , JOB_ID  FROM EMPLOYEES e WHERE MANAGER_ID IS NULL;

SELECT department_id FROM EMPLOYEES e WHERE JOB_ID ='ST_CLERK' AND DEPARTMENT_ID IS NOT NULL ;
SELECT department_id FROM EMPLOYEES e WHERE JOB_ID !='ST_CLERK' AND DEPARTMENT_ID IS NOT NULL ;

SELECT EMPLOYEE_ID , FIRST_NAME , JOB_ID , SALARY * COMMISSION_PCT AS COMMISSION FROM EMPLOYEES e WHERE COMMISSION_PCT IS NOT NULL ;

SELECT
	first_name,
	last_name,
	email,
	phone_number,
	LOWER(job_id)
FROM
	EMPLOYEES e
WHERE
	FIRST_NAME = 'Curtis';

SELECT
	EMPLOYEE_ID ,
	FIRST_NAME ,
	HIRE_DATE ,
	REPLACE (JOB_ID, 'IT_PROG',
	'PROGRAMMER')
FROM
	EMPLOYEES e
WHERE
	DEPARTMENT_ID IN (60, 70, 80, 90);

SELECT
	EMPLOYEE_ID ,
	FIRST_NAME || ' ' || LAST_NAME AS name,
	JOB_ID
FROM
	EMPLOYEES e
WHERE JOB_ID IN ('AD_PRES','PU_CLERK')


SELECT
	LAST_NAME ,
	SALARY ,
	CASE 
		WHEN SALARY BETWEEN 0 AND 1999 THEN SALARY * 1
		WHEN SALARY BETWEEN 2000 AND 3999 THEN SALARY * 1.09 
		WHEN SALARY BETWEEN 4000 AND 5999 THEN SALARY * 1.2
		WHEN SALARY BETWEEN 6000 AND 7999 THEN SALARY * 1.3
		WHEN SALARY BETWEEN 8000 AND 9999 THEN SALARY * 1.4
		WHEN SALARY BETWEEN 10000 AND 11999 THEN SALARY * 1.42
		WHEN SALARY BETWEEN 12000 AND 13999 THEN SALARY * 1.44
		ELSE SALARY * 1.45
	END AS TAX_RATE
FROM
	EMPLOYEES e ORDER BY SALARY ASC ;

SELECT
	LAST_NAME ,
	SALARY ,
	CASE TRUNC(SALARY / 2000, 0)
		WHEN 0 THEN '0%'
		WHEN 1 THEN '9%' 
		WHEN 2 THEN '20%'
		WHEN 3 THEN '30%'
		WHEN 4 THEN '40%'
		WHEN 5 THEN '42%'
		WHEN 6 THEN '44%'
		ELSE '45%'
	END AS TAX_RATE
FROM
	EMPLOYEES e WHERE DEPARTMENT_ID = 80 ORDER BY SALARY ASC ;

SELECT MAX(SALARY) - MIN(SALARY)  FROM EMPLOYEES e;
SELECT COUNT(DISTINCT MANAGER_ID) FROM EMPLOYEES e ; 

SELECT DEPARTMENT_ID , COUNT(DISTINCT  EMPLOYEE_ID) FROM EMPLOYEES e GROUP BY DEPARTMENT_ID ORDER BY DEPARTMENT_ID ;
SELECT
	DEPARTMENT_ID ,
	AVG(SALARY)
FROM
	EMPLOYEES e
GROUP BY
	DEPARTMENT_ID
ORDER BY
	DEPARTMENT_ID;

SELECT
	JOB_ID ,
	COUNT(EMPLOYEE_ID)
FROM
	EMPLOYEES e
GROUP BY
	JOB_ID
ORDER BY
	JOB_ID ;

SELECT MANAGER_ID ,MIN(SALARY) FROM EMPLOYEES e WHERE MANAGER_ID IS NOT NULL GROUP BY MANAGER_ID HAVING MIN(SALARY) >= 6000 ORDER BY MANAGER_ID ;

-- ----------------------------------------------------------------

SELECT
	e.HIRE_DATE,
	e.LAST_NAME,
	e.MANAGER_Id,
	jh.START_DATE
FROM
	EMPLOYEES e
JOIN JOB_HISTORY jh ON
	e.EMPLOYEE_ID = jh.EMPLOYEE_ID ;

SELECT
	e.employee_id AS myId,
	e.hire_date AS myHD,
	e2.EMPLOYEE_ID AS MGRID,
	e2.HIRE_DATE AS MGRHD
FROM
	EMPLOYEES e
JOIN EMPLOYEES e2 ON
	e.manager_id = e2.EMPLOYEE_ID AND e.hire_date < e2.HIRE_DATE ;

-- ----------------------------------------------------------------

SELECT
	e.EMPLOYEE_ID,
	e.LAST_NAME ,
	e.DEPARTMENT_ID,
	l.CITY 
FROM
	EMPLOYEES e
JOIN DEPARTMENTS d ON
	e.DEPARTMENT_ID = d.DEPARTMENT_ID
JOIN LOCATIONS l ON
	d.LOCATION_ID = l.LOCATION_ID 
--WHERE SUBSTR(l.CITY, 1, 1) = 'T';
WHERE l.CITY LIKE 'T%'

-- ----------------------------------------------------------------

SELECT
	e.EMPLOYEE_ID ,
	e.LAST_NAME ,
	e.DEPARTMENT_ID ,
	e.SALARY,
	d.LOCATION_ID
FROM
	LOCATIONS l
JOIN DEPARTMENTS d ON
	l.LOCATION_ID = d.LOCATION_ID
JOIN EMPLOYEES e ON
	e.DEPARTMENT_ID = d.DEPARTMENT_ID
WHERE
	d.LOCATION_ID = 1700
ORDER BY e.EMPLOYEE_ID ASC ;


-- ----------------------------------------------------------------

SELECT
	d.DEPARTMENT_ID,
	d.LOCATION_ID ,
	COUNT(e.DEPARTMENT_ID) AS countDEPTID,
	ROUND(AVG(e.SALARY), 2) AS AVGSAL
FROM
	DEPARTMENTS d
JOIN EMPLOYEES e ON
	d.DEPARTMENT_ID = e.DEPARTMENT_ID
GROUP BY
	d.DEPARTMENT_ID ,
	LOCATION_ID ;

-- ----------------------------------------------------------------

SELECT
	e.DEPARTMENT_ID ,
	e.LAST_NAME ,
	d.DEPARTMENT_NAME
FROM
	DEPARTMENTS d
JOIN EMPLOYEES e ON
	d.DEPARTMENT_id = e.DEPARTMENT_id
WHERE
	d.DEPARTMENT_NAME = 'Executive';

-- ----------------------------------------------------------------
-- concat
SELECT
	DISTINCT e.department_id ,
	e.SALARY,
	e.HIRE_DATE,
--	CONCAT(e.FIRST_NAME, CONCAT(' ', e.LAST_NAME)) AS FLName
	e.first_name || ' ' || e.last_name AS myName
FROM
	EMPLOYEES e
JOIN EMPLOYEES e2 ON
	e.department_id = e2.DEPARTMENT_ID
AND e.salary < e2.salary
AND e.hire_date < e2.hire_date;

-- ----------------------------------------------------------------

select DEPARTMENT_ID , LAST_NAME  from EMPLOYEES e WHERE DEPARTMENT_ID IN (select DISTINCT DEPARTMENT_ID  from EMPLOYEES e WHERE last_name LIKE '%U%') ORDER BY e.EMPLOYEE_ID ;

SELECT
	e.EMPLOYEE_ID ,
	e.JOB_ID 
FROM
	EMPLOYEES e
WHERE
	(e.EMPLOYEE_ID,
	e.JOB_ID) IN (
	SELECT
		jh.employee_id,
		jh.job_id
	FROM
		JOB_HISTORY jh)
	ORDER BY e.EMPLOYEE_ID ASC ;

-- --------------------------------------------------------------
SELECT
	e.job_id,
	(
	SELECT
		SUM(e2.SALARY) 
	FROM
		EMPLOYEES e2 
	WHERE
		 e2.department_id = 10 AND e.JOB_ID = e2.job_id) AS d10,
	(
	SELECT
		SUM(e2.SALARY) 
	FROM
		EMPLOYEES e2 
	WHERE
		 e2.department_id = 20 AND e.JOB_ID = e2.job_id) AS d20,
	(
	SELECT
		SUM(e2.SALARY) 
	FROM
		EMPLOYEES e2 
	WHERE
		 e2.department_id = 30 AND e.JOB_ID = e2.job_id) as d30,
	(
	SELECT
		SUM(e2.SALARY) 
	FROM
		EMPLOYEES e2 
	WHERE
		 e2.department_id = 40 AND e.JOB_ID = e2.job_id) as d40,
	(
	SELECT
		SUM(e2.SALARY) 
	FROM
		EMPLOYEES e2 
	WHERE
		 e2.department_id = 50 AND e.JOB_ID = e2.job_id) AS d50,
	(
	SELECT
		SUM(e2.SALARY) 
	FROM
		EMPLOYEES e2 
	WHERE
		 e2.department_id = 60 AND e.JOB_ID = e2.job_id) AS d60,
	(
	SELECT
		SUM(e2.SALARY) 
	FROM
		EMPLOYEES e2 
	WHERE
		 e2.department_id = 70 AND e.JOB_ID = e2.job_id) AS d70,
	(
	SELECT
		SUM(e2.SALARY) 
	FROM
		EMPLOYEES e2 
	WHERE
		 e2.department_id = 80 AND e.JOB_ID = e2.job_id) AS d80,
	(
	SELECT
		SUM(e2.SALARY) 
	FROM
		EMPLOYEES e2 
	WHERE
		 e2.department_id = 90 AND e.JOB_ID = e2.job_id) AS d90,
	(
	SELECT
		SUM(e2.SALARY) 
	FROM
		EMPLOYEES e2 
	WHERE
		 e2.department_id = 100 AND e.JOB_ID = e2.job_id) AS d100,
	(
	SELECT
		SUM(e2.SALARY) 
	FROM
		EMPLOYEES e2 
	WHERE
		 e2.department_id = 110 AND e.JOB_ID = e2.job_id) AS d110,
	(
	SELECT
		SUM(e2.SALARY) 
	FROM
		EMPLOYEES e2 
	WHERE
		  e.JOB_ID = e2.job_id) AS total
FROM
	EMPLOYEES e 
GROUP BY e.JOB_ID
ORDER BY e.JOB_ID ;


-- --------------------------------------------------------------------------------

SELECT
	e.LAST_NAME,
	e.JOB_ID,
	e.SALARY
FROM
	EMPLOYEES e
WHERE
	SALARY > (
	SELECT
		max(e2.salary)
	FROM
		EMPLOYEES e2
	WHERE
		JOB_ID = 'SA_MAN');

-- ----------------------------------------------------------------------------

SELECT
	LAST_NAME ,
	DEPARTMENT_ID,
	SALARY
FROM
	EMPLOYEES e
WHERE
	(e.DEPARTMENT_ID ,
	SALARY ) IN (
	SELECT
		DEPARTMENT_ID ,
		SALARY
	FROM
		EMPLOYEES e
	WHERE
		COMMISSION_PCT IS NOT NULL );

-- ----------------------------------------------------------------------------
SELECT
	EMPLOYEE_ID ,
	LAST_NAME ,
	SALARY
FROM
	EMPLOYEES e
WHERE
	DEPARTMENT_ID IN (
	SELECT
		DISTINCT DEPARTMENT_ID
	FROM
		EMPLOYEES e
	WHERE
		SALARY > (
		SELECT
			avg(e.SALARY)
		FROM
			EMPLOYEES e)
		AND LAST_NAME LIKE '%u%');
	
-- ----------------------------------------------------------------------------
SELECT
	LAST_NAME ,
	E1.DEPARTMENT_ID ,
	SALARY ,
	E2.deptSALAVG
FROM
	EMPLOYEES E1,
	(
	SELECT
		DEPARTMENT_ID ,
		AVG(SALARY) AS deptSALAVG
	FROM
		EMPLOYEES e
	GROUP BY
		DEPARTMENT_ID) E2
WHERE
	E1.DEPARTMENT_ID = E2.DEPARTMENT_ID
	AND E1.SALARY > E2.deptSALAVG
ORDER BY
	DEPARTMENT_ID ;
	
	
-- ----------------------------------------------------------------------------
SELECT
	LAST_NAME ,
	HIRE_DATE
FROM
	EMPLOYEES e
WHERE
	HIRE_DATE > (
	SELECT
		HIRE_DATE
	FROM
		EMPLOYEES e
	WHERE
		LAST_NAME = 'Davies')
	
	
SELECT
	LAST_NAME ,
	salary
FROM
	EMPLOYEES e
WHERE
	MANAGER_ID IN (
	SELECT
		EMPLOYEE_ID
	FROM
		EMPLOYEES e
	WHERE
		LAST_NAME = 'King')
	
-- ----------------------------------------------------------------------------
SELECT
	LAST_NAME,
	DEPARTMENT_ID ,
	SALARY
FROM
	EMPLOYEES e 
	WHERE (SALARY , NVL(COMMISSION_PCT, 0)) IN  (
	SELECT
		SALARY ,
		NVL(COMMISSION_PCT, 0)
	FROM
		EMPLOYEES e
	WHERE
		LAST_NAME = 'Kochhar')AND e.LAST_NAME != 'Kochhar';
		
-- ----------------------------------------------------------------------------
SELECT
	COUNTRY_ID ,
	COUNTRY_NAME
FROM
	COUNTRIES c
WHERE
	c.COUNTRY_ID IN (
	SELECT
		l.COUNTRY_ID
	FROM
		LOCATIONS l ,
		(
		SELECT
			LOCATION_ID
		FROM
			DEPARTMENTS d ) D
	WHERE
		l.LOCATION_ID = d.location_id);
-- ----------------------------------------------------------------------------

SELECT
	 DISTINCT TO_CHAR(HIRE_DATE, 'YYYY') AS HIRE_DATE ,
	(SELECT COUNT(EMPLOYEE_ID) FROM EMPLOYEES ) AS allemployees,
	(SELECT count(EMPLOYEE_ID) FROM EMPLOYEES WHERE TO_CHAR(HIRE_DATE, 'YYYY') = '2013') AS y2013,
	(SELECT COUNT(EMPLOYEE_ID) FROM EMPLOYEES WHERE TO_CHAR(HIRE_DATE, 'YYYY') = '2014') AS y2014,
	(SELECT COUNT(EMPLOYEE_ID) FROM EMPLOYEES WHERE TO_CHAR(HIRE_DATE, 'YYYY') = '2015') AS y2015,
	(SELECT COUNT(EMPLOYEE_ID) FROM EMPLOYEES WHERE TO_CHAR(HIRE_DATE, 'YYYY') = '2016') AS y2016
FROM
	EMPLOYEES e 
GROUP BY HIRE_DATE 
ORDER BY HIRE_DATE ;


select * from EMPLOYEES e WHERE HIRE_DATE LIKE '%13';

select * from EMPLOYEES e WHERE HIRE_DATE LIKE '13%';

select * from EMPLOYEES e WHERE HIRE_DATE LIKE '%13%';
-- ----------------------------------------------------------------------------
SELECT
	COUNT(employee_id) AS allm,
	(SELECT count(EMPLOYEE_ID) FROM EMPLOYEES WHERE TO_CHAR(HIRE_DATE, 'YY') = '13') AS y2013,
	(SELECT COUNT(EMPLOYEE_ID) FROM EMPLOYEES WHERE TO_CHAR(HIRE_DATE, 'YY') = '14') AS y2014,
	(SELECT COUNT(EMPLOYEE_ID) FROM EMPLOYEES WHERE TO_CHAR(HIRE_DATE, 'YY') = '15') AS y2015,
	(SELECT COUNT(EMPLOYEE_ID) FROM EMPLOYEES WHERE TO_CHAR(HIRE_DATE, 'YY') = '16') AS y2016
FROM EMPLOYEES e ;


-- ----------------------------------------------------------------------------

SELECT
	EMPLOYEE_ID ,
	FIRST_NAME || ' ' || LAST_NAME AS name,
	DEPARTMENT_ID ,
	SALARY
FROM
	EMPLOYEES e
WHERE(SALARY, NVL(COMMISSION_PCT, 0)) IN 
	(
	SELECT
		SALARY ,
		NVL(COMMISSION_PCT, 0)
	FROM
		EMPLOYEES e
	WHERE
		DEPARTMENT_ID IN (
		SELECT
			DEPARTMENT_ID
		FROM
			DEPARTMENTS d
		WHERE
			d.location_id = 1700));


CREATE TABLE IDX_EMPLYOEES AS SELECT DISTINCT  FIRST_NAME, LAST_NAME, HIRE_DATE FROM EMPLOYEES e ;

CREATE INDEX IDX_NAME ON IDX_EMPLYOEES();
CREATE INDEX IDX_NAME ON IDX_EMPLYOEES(FIRST_NAME);
SELECT * FROM IDX_EMPLYOEES WHERE FIRST_NAME='JACK';
DROP INDEX IDX_EMP_SAL;







