--employees 

SELECT * FROM EMPLOYEES e ;
SELECT first_name, LAST_name, job_id FROM EMPLOYEES e;

SELECT EMPLOYEE_ID, LAST_NAME, SALARY FROM EMPLOYEES WHERE EMPLOYEE_ID = 176 ;
SELECT LAST_NAME , salary FROM EMPLOYEES WHERE SALARY >= 12000;
SELECT Last_name, salary FROM EMPLOYEES WHERE SALARY < 5000 OR SALARY > 12000;

SELECT
	LAST_NAME ,
	DEPARTMENT_ID
FROM
	EMPLOYEES
WHERE
	DEPARTMENT_ID IN (20, 50)
ORDER BY
	LAST_NAME,
	DEPARTMENT_ID;

SELECT
	LAST_NAME,
	salary,
	COMMISSION_PCT
FROM
	EMPLOYEES
WHERE
	COMMISSION_PCT IS NOT NULL;

SELECT
	*
FROM
	EMPLOYEES
WHERE
	SALARY NOT IN (2500, 3500, 7000)
	AND JOB_ID IN ('SA_REP', 'ST_CLERK');

SELECT LAST_NAME , EMPLOYEE_ID , HIRE_DATE  FROM EMPLOYEES WHERE HIRE_DATE > '2017-01-01' AND HIRE_DATE < '2017-12-31';

SELECT Last_name, salary FROM EMPLOYEES WHERE SALARY BETWEEN 5000 AND 12000 ORDER BY SALARY ASC ;
SELECT LAST_NAME , EMPLOYEE_ID , HIRE_DATE  FROM EMPLOYEES WHERE HIRE_DATE BETWEEN '2017-01-01' AND '2017-12-31' ORDER BY HIRE_DATE ;

SELECT EMPLOYEE_ID , LAST_NAME FROM EMPLOYEES e WHERE LAST_NAME LIKE '%u%';
SELECT EMPLOYEE_ID , LAST_NAME FROM EMPLOYEES e WHERE LAST_NAME LIKE '___a%';
SELECT EMPLOYEE_ID , LAST_NAME FROM EMPLOYEES e WHERE LAST_NAME LIKE '%a%e%' ORDER BY LAST_NAME ASC;

SELECT LAST_NAME , JOB_ID  FROM EMPLOYEES e WHERE MANAGER_ID IS NULL;

SELECT department_id FROM EMPLOYEES e WHERE JOB_ID ='ST_CLERK' AND DEPARTMENT_ID IS NOT NULL ;
SELECT department_id FROM EMPLOYEES e WHERE JOB_ID !='ST_CLERK' AND DEPARTMENT_ID IS NOT NULL ;

SELECT EMPLOYEE_ID , FIRST_NAME , JOB_ID , SALARY * COMMISSION_PCT AS COMMISSION FROM EMPLOYEES e WHERE COMMISSION_PCT IS NOT NULL ;

SELECT
	first_name,
	last_name,
	email,
	phone_number,
	LOWER(job_id)
FROM
	EMPLOYEES e
WHERE
	FIRST_NAME = 'Curtis';

SELECT
	EMPLOYEE_ID ,
	FIRST_NAME ,
	HIRE_DATE ,
	REPLACE (JOB_ID, 'IT_PROG',
	'PROGRAMMER')
FROM
	EMPLOYEES e
WHERE
	DEPARTMENT_ID IN (60, 70, 80, 90);

SELECT
	EMPLOYEE_ID ,
	FIRST_NAME || ' ' || LAST_NAME AS name,
	JOB_ID
FROM
	EMPLOYEES e
WHERE JOB_ID IN ('AD_PRES','PU_CLERK')





