--employees 

SELECT * FROM EMPLOYEES e ;
SELECT first_name, LAST_name, job_id FROM EMPLOYEES e;

SELECT EMPLOYEE_ID, LAST_NAME, SALARY FROM EMPLOYEES WHERE EMPLOYEE_ID = 176 ;
SELECT LAST_NAME , salary FROM EMPLOYEES WHERE SALARY >= 12000;
SELECT Last_name, salary FROM EMPLOYEES WHERE SALARY < 5000 OR SALARY > 12000;

SELECT
	LAST_NAME ,
	DEPARTMENT_ID
FROM
	EMPLOYEES
WHERE
	DEPARTMENT_ID IN (20, 50)
ORDER BY
	LAST_NAME,
	DEPARTMENT_ID;

SELECT
	LAST_NAME,
	salary,
	COMMISSION_PCT
FROM
	EMPLOYEES
WHERE
	COMMISSION_PCT IS NOT NULL;

SELECT
	*
FROM
	EMPLOYEES
WHERE
	SALARY NOT IN (2500, 3500, 7000)
	AND JOB_ID IN ('SA_REP', 'ST_CLERK');
	
SELECT LAST_NAME , EMPLOYEE_ID , HIRE_DATE  FROM EMPLOYEES WHERE HIRE_DATE > '2017-01-01' AND HIRE_DATE < '2017-12-31';

SELECT Last_name, salary FROM EMPLOYEES WHERE SALARY BETWEEN 5000 AND 12000 ORDER BY SALARY ASC ;
SELECT LAST_NAME , EMPLOYEE_ID , HIRE_DATE  FROM EMPLOYEES WHERE HIRE_DATE BETWEEN '2017-01-01' AND '2017-12-31' ORDER BY HIRE_DATE ;
