--scott

--SELECT 
SELECT * FROM EMP e;
SELECT * FROM DEPT d

SELECT
	EMPNO,
	ENAME,
	JOB
FROM
	emp;

SELECT
	EMPNO,
	MGR,
	DEPTNO
FROM
	emp;
	
SELECT DISTINCT deptno FROM EMP e ;
SELECT empno as 사원번호, MGR 매니저번호, deptno "부서 번호" FROM EMP e ;

SELECT EMPNO, SAL, SAL * 12 + COMM AS 연봉 FROM EMP e ;

SELECT * FROM EMP ORDER BY SAL DESC ;
SELECT * FROM EMP ORDER BY SAL ASC ;
SELECT empno, ename, sal FROM EMP ORDER BY EMPNO DESC ;

SELECT * FROM EMP ORDER BY DEPTNO ASC, SAL DESC ;
SELECT * FROM EMP ORDER BY DEPTNO, SAL DESC ;

SELECT * FROM EMP e WHERE DEPTNO = 30 OR SAL >= 1000;
SELECT * FROM EMP e WHERE DEPTNO = 30;
SELECT * FROM EMP e WHERE SAL >= 1000;
SELECT * FROM EMP e WHERE SAL >= 1000 ORDER BY SAL  DESC;

SELECT * FROM EMP e WHERE EMPNO = 7782;

SELECT  * FROM EMP e  WHERE DEPTNO = 30 AND JOB ='SALESMAN';

SELECT * FROM EMP e  WHERE EMPNO = 7499 AND DEPTNO = 30;
SELECT * FROM EMP e  WHERE DEPTNO = 30 OR JOB = 'SALESMAN';

SELECT * FROM EMP e WHERE ENAME >= 'F';

SELECT * FROM EMP e WHERE SAL != 3000;
SELECT * FROM EMP e WHERE SAL <> 3000;
SELECT * FROM EMP e  WHERE SAL ^= 3000;

SELECT * FROM EMP e  WHERE JOB = 'MANAGER' OR JOB = 'SALESMAN' OR JOB = 'CLERK';

-- in
SELECT * FROM EMP e  WHERE JOB IN ('MANAGER', 'SALESMAN', 'CLERK');

SELECT  * FROM EMP e WHERE HIREDATE > '1981-10-31';

SELECT  * FROM EMP  WHERE SAL BETWEEN 2000 AND 3000;
